CREATE TABLE `tbl_usuarios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `email` VARCHAR(300) NOT NULL,
  `senha` VARCHAR(300) NOT NULL,
  `foto` VARCHAR(300) NOT NULL,
  `status` BOOLEAN NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  `documento` VARCHAR(300) NOT NULL,
  `rua` VARCHAR(300) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(300) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(300) NOT NULL,
  `cidade` VARCHAR(300) NOT NULL,
  `estado` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE
);